// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4m9892MMC-1tB64WoEYDEpV475ESTeDw',
    appId: '1:603668459865:web:1e7800a5627f58f04e1c48',
    messagingSenderId: '603668459865',
    projectId: 'healthyfy-85a54',
    authDomain: 'healthyfy-85a54.firebaseapp.com',
    databaseURL: 'https://healthyfy-85a54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthyfy-85a54.appspot.com',
    measurementId: 'G-6T44LKGGYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOKzJ-L5YsAYsXE2OZ1GCH7HbE2LoRTIM',
    appId: '1:603668459865:android:9f4e25146a2fc1ce4e1c48',
    messagingSenderId: '603668459865',
    projectId: 'healthyfy-85a54',
    databaseURL: 'https://healthyfy-85a54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthyfy-85a54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWXKR7EJqW4fINNLX7OTsy5IM3G3xAzFc',
    appId: '1:603668459865:ios:6f57e384de875fc84e1c48',
    messagingSenderId: '603668459865',
    projectId: 'healthyfy-85a54',
    databaseURL: 'https://healthyfy-85a54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthyfy-85a54.appspot.com',
    iosClientId: '603668459865-sag0ape9bjuu6kbh7rd08746rgoa8rt2.apps.googleusercontent.com',
    iosBundleId: 'com.healtyfy.healtyfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWXKR7EJqW4fINNLX7OTsy5IM3G3xAzFc',
    appId: '1:603668459865:ios:6f57e384de875fc84e1c48',
    messagingSenderId: '603668459865',
    projectId: 'healthyfy-85a54',
    databaseURL: 'https://healthyfy-85a54-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthyfy-85a54.appspot.com',
    iosClientId: '603668459865-sag0ape9bjuu6kbh7rd08746rgoa8rt2.apps.googleusercontent.com',
    iosBundleId: 'com.healtyfy.healtyfy',
  );
}
