// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARB8XPwVr-PxLlqaA8j3htoUK574HgV-Y',
    appId: '1:199756302480:web:3bd189a56012d44f9df015',
    messagingSenderId: '199756302480',
    projectId: 'healtyfy-pal',
    authDomain: 'healtyfy-pal.firebaseapp.com',
    databaseURL: 'https://healtyfy-pal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healtyfy-pal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBt87_5vhMFymmHCwZR5A0Av18I-Hh80A',
    appId: '1:199756302480:android:ed7c38ba00cf46e59df015',
    messagingSenderId: '199756302480',
    projectId: 'healtyfy-pal',
    databaseURL: 'https://healtyfy-pal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healtyfy-pal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClGUtLE3vcURCfi-9jcqf8jiIhbT4hJRk',
    appId: '1:199756302480:ios:612e0d75c83651719df015',
    messagingSenderId: '199756302480',
    projectId: 'healtyfy-pal',
    databaseURL: 'https://healtyfy-pal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healtyfy-pal.appspot.com',
    androidClientId: '199756302480-25bkeuk275jvtbph47p2i8io3mnt481s.apps.googleusercontent.com',
    iosClientId: '199756302480-qtvtfn0ha99sh91s2l4q4o09idqpfdt0.apps.googleusercontent.com',
    iosBundleId: 'com.healtyfy.healtyfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClGUtLE3vcURCfi-9jcqf8jiIhbT4hJRk',
    appId: '1:199756302480:ios:612e0d75c83651719df015',
    messagingSenderId: '199756302480',
    projectId: 'healtyfy-pal',
    databaseURL: 'https://healtyfy-pal-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healtyfy-pal.appspot.com',
    androidClientId: '199756302480-25bkeuk275jvtbph47p2i8io3mnt481s.apps.googleusercontent.com',
    iosClientId: '199756302480-qtvtfn0ha99sh91s2l4q4o09idqpfdt0.apps.googleusercontent.com',
    iosBundleId: 'com.healtyfy.healtyfy',
  );
}
